# SPDX-FileCopyrightText: 2025 The University of St Andrews
# SPDX-License-Identifier: CC0-1.0

name: REUSE
on: push

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v5

  generate-spdx-bom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate SPDX BOM
        uses: fsfe/reuse-action@v5
        with:
          args: spdx
